README.md, docs/about/development.md, docs/documentation/database.md, docs/documentation/hardpy_panel.md, docs/documentation/pytest_hardpy.md, docs/documentation/structure.md, docs/examples/couchdb_load.md, docs/examples/db_in_ram.md, docs/examples/hello_hardpy.md, docs/examples/minute_parity.md, docs/examples/multiple_stands.md, docs/examples/skip_test.md, docs/features/features.md, docs/index.md, hardpy/__init__.py, hardpy/pytest_hardpy/pytest_call.py, hardpy/pytest_hardpy/utils/__init__.py, hardpy/pytest_hardpy/utils/exception.py, mkdocs.yml, tests/test_func.py
- Added documentation
- Fix dut serial number storing
=> Add documentation

README.md, docs/changelog.md, docs/index.md, examples/project/minute_parity/test_3.py, hardpy/hardpy_panel/api.py, hardpy/hardpy_panel/runner.py, tests/conftest.py
=> Release 0.2.0

docs/examples/skip_test.md
Corrected instruction for skipped tests end example of code
=> Correct dependency instruction

docs/examples/multiple_stands.md
The instructions for storing reports (as part of the multiple stands instruction) have been supplemented with a more detailed description of the actions.
=> Change storing reports guide

docs/documentation/database.md, docs/examples/db_in_ram.md
DB instructions and RAM instructions corrected
=> Correct db and ram instructions

docs/changelog.md, pyproject.toml
Update package version to 0.3.0.
=> Release 0.3.0

tests/test_func.py, tests/test_mark.py
- Added unit tests with failed tests to test_func and test_mark, which test checking income data
=> Add unit tests with failed tests

hardpy/hardpy_panel/frontend/src/hardpy_test_view/RunTimer.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/SuiteList_v3.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestSuite_v3.tsx
Fixed a bug with displaying a dialog box after completing tests and refreshing the page
=> Fix a bug with displaying a dialog box after completing tests and refreshing the page

docs/changelog.md, docs/documentation/database.md, docs/documentation/pytest_hardpy.md, docs/examples/dialog_box.md, examples/project/dialog_box/test_1_base_box.py, examples/project/dialog_box/test_2_input_field.py, examples/project/dialog_box/test_3_choice_control.py, examples/project/dialog_box/test_4_send_image.py, hardpy/__init__.py, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestSuite_v3.tsx, hardpy/pytest_hardpy/pytest_call.py, hardpy/pytest_hardpy/utils/__init__.py, hardpy/pytest_hardpy/utils/dialog_box.py
* Refactor dialog box API;
* Fix checkbox widget;
* Refactor fronend naming;
=> Refactor dialog box API

README.md, docs/about/development.md, docs/index.md, pyproject.toml, scripts/compile_front.sh, scripts/recompile_front.sh
* Added project urls to `pyproject.toml`.
* Change `pip3` and `python3` to `pip` and `python`.
=> Add project urls

docs/examples/dialog_box.md, examples/project/dialog_box/test_5_multiple_steps.py, hardpy/__init__.py
* Fix imports in dialog_box.md
* Fix imports in root __init__
=> Fix imports

docs/changelog.md, pyproject.toml
* Update pyproject.toml to 0.6.0.
* Update changelog.md to 0.6.0.
=> HardPy version 0.6.0-rc1

docs/changelog.md, hardpy/pytest_hardpy/result/couchdb_config.py, pyproject.toml
Changed `connection_string` creation in `CouchdbConfig` to work with cloud couchdb.
=> Release 0.5.1

docs/changelog.md, examples/couchdb_load/pytest.ini, examples/dialog_box/pytest.ini, examples/hello_hardpy/pytest.ini, examples/minute_parity/pytest.ini, hardpy/cli/template.py, hardpy/pytest_hardpy/db/base_connector.py, hardpy/pytest_hardpy/plugin.py, hardpy/pytest_hardpy/utils/connection_data.py, tests/test_plugin/database/couchdb.ini, tests/test_plugin/docker-compose.yaml, tests/test_plugin/test_pytest.py
Fix running tests with a simple `pytest` command.
It is now possible to run tests with the `pytests` command when the hardpy panel is running.
=> Release 0.6.1

docs/changelog.md, examples/couchdb_load/pytest.ini, examples/dialog_box/pytest.ini, examples/hello_hardpy/pytest.ini, examples/minute_parity/pytest.ini, hardpy/pytest_hardpy/db/base_connector.py, hardpy/pytest_hardpy/plugin.py, hardpy/pytest_hardpy/utils/connection_data.py, pyproject.toml, tests/test_plugin/database/couchdb.ini, tests/test_plugin/docker-compose.yaml, tests/test_plugin/test_pytest.py
Update `develop` branch to 0.6.1
=> Update develop to 0.6.1

README.md, docs/index.md, pyproject.toml
* Fix license and python version in **pyproject.toml**.
* Removed links from **index.md**.
* Added badges to **README**.
=> Minor beauti fixes

README.md
Update pypi badge source to https://img.shields.io/pypi/v/hardpy
=> Update pypi badge

mkdocs.yml
Added theme color mode switcher.
**Light**
**Dark**
=> Color theme mode switcher

.ruff.toml, docs/changelog.md, docs/documentation/pytest_hardpy.md, docs/documentation/stand_cloud.md, docs/examples/stand_cloud.md, examples/stand_cloud/conftest.py, hardpy/cli/cli.py, hardpy/common/stand_cloud/connector.py, hardpy/common/stand_cloud/registration.py, hardpy/pytest_hardpy/plugin.py, hardpy/pytest_hardpy/result/report_loader/stand_cloud_loader.py, pyproject.toml
* Add `requsts.Response` object to `load` and `healthcheck` methods of `StandCloudLoader` class.
* Update documentation.
* Fix **StandCloud API** service address.
* Add `jinja2` package for auth page creation.
=> StandCloud fix

docs/documentation/stand_cloud.md
Change **StandCloud** image path to the `raw.githubusercontent.com`
=> Fix StandCloud image path

docs/changelog.md, docs/documentation/stand_cloud.md, hardpy/common/stand_cloud/registration.py, hardpy/common/stand_cloud/token_storage.py, pyproject.toml
Fix StandCloud authorization process in Windows.
=> Fix StandCloud authorization 

hardpy/hardpy_panel/frontend/src/App.test.tsx, hardpy/hardpy_panel/frontend/src/App.tsx, hardpy/hardpy_panel/frontend/src/button/StartStop.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/DialogBox.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/OperatorMsg.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/PlaySound.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/RunTimer.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/SuiteList.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestData.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestName.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestNumber.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestStatus.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestSuite.tsx, hardpy/hardpy_panel/frontend/src/index.tsx, hardpy/hardpy_panel/frontend/src/notifying/Jtds.tsx, hardpy/hardpy_panel/frontend/src/progress/ProgressView.tsx, hardpy/hardpy_panel/frontend/src/reportWebVitals.ts, hardpy/hardpy_panel/frontend/src/restart_alert/RestartAlert.tsx, hardpy/hardpy_panel/frontend/src/setupTests.ts
Al  frontend files were formatted with Prettier
=> Formatting with prettier

hardpy/hardpy_panel/frontend/src/App.tsx, hardpy/hardpy_panel/frontend/src/button/StartStop.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/DialogBox.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/OperatorMsg.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/PlaySound.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/RunTimer.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/SuiteList.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestData.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestName.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestNumber.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestStatus.tsx, hardpy/hardpy_panel/frontend/src/hardpy_test_view/TestSuite.tsx, hardpy/hardpy_panel/frontend/src/index.tsx, hardpy/hardpy_panel/frontend/src/progress/ProgressView.tsx
- Linter errors fixed
- Image, HTML, checkbox, and radio button components extracted
- Frontend visual elements redesigned
=> Frontend refactoring

docs/documentation/pytest_hardpy.md, docs/examples/stand_cloud.md, examples/stand_cloud/conftest.py
Fix **StandCloud** operator message example.
=> Fix StandCloud operator message example

.vscode/launch.json, docs/changelog.md, docs/documentation/hardpy_panel.md, docs/examples/minute_parity.md, examples/minute_parity/test_1.py, hardpy/hardpy_panel/frontend/src/hardpy_test_view/SuiteList.tsx
- Added the **Stand info** field to the operator panel
=> Add stand info to operator panel

docs/changelog.md, pyproject.toml
- 0.12.0-rc1
- Updated package version to 0.12.0
=> Update package version to 0.12.0

docs/changelog.md, pyproject.toml
Update package version to 0.14.0 in pyproject.toml and changelog.
=> Update package to 0.14.0

docs/features/features.md
Correct Chinese language in **features.md**.
=> Correct Chinese language

docs/changelog.md, pyproject.toml
=> Update package to 0.15.0

README.md
=> Reddit and Telegram badges
