.flake8, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/mr.yml, .github/workflows/release.yml, .github/workflows/test.yml
The MR adds workflows for
- Merge Requests
- Releases
- Main branch continuous integration 
All of them are combinations of auxiliary workflows:
- Lint (flake8)
- Test (pytest)
- Build
Release workflow in addition include deployment jobs:
- GitHub
- TestPyPi
- PyPi
The release also includes protecting check that prevent deploy python package with non-matching git tag.
A workflow that includes Lint and Test stages shows in its summary page the result of runs: list of warnings, errors, and test results table. In addition, Merge Requests in the file diffs page shows annotations generated by the Lint stage.
Flake8 config wile has a change that disable explicit format set to 'wemake'. For some reason, it breaks GitHub annotations.
=> GitHub workflows

.github/workflows/docs.yml
This GitHub workflow builds docs and creates `gh-pages` branch for deployment to Pages.
Be sure settings for GitHub Pages set the correct branch.
Generated [docs preview](https://ila-embsys.github.io/hardpy/) was tested on my fork.
=> Add build MkDocs action

docs/changelog.md, hardpy/pytest_hardpy/db/base_store.py, hardpy/pytest_hardpy/plugin.py, hardpy/pytest_hardpy/pytest_call.py, hardpy/pytest_hardpy/reporter/base.py, hardpy/pytest_hardpy/reporter/hook_reporter.py
* Accelerated collection of tests. When tests collected, `glom.assign` is replaced by the default dict call. `glom.assign` is too longer function for collection.
```python
def update_doc(self, key: str, value):
if "." in key:
assign(self._doc, key, value)
else:
self._doc[key] = value
```
* Reduced the number of database calls. Database update is now a separate function `update_db_by_doc()`.
* Added correct handling of pycouchdb exception `Conflict` in `update_db` method.
* Refactored some function names and their logic.
=> Speed up test collection

mkdocs.yml
Added links to the repository to the header of the documentation site.
It was:
It became:
=> Repository links

hardpy/pytest_hardpy/plugin.py
1. Removed ANSI codes from frontend. Fix problem with ANSI codes in pytest terminal output in operator panel (image).
2. Added an exception handler for an exception in the pytest fixture, like DriverExample in the minute parity example.
=> Remove ansi codes from frontend

docs/about/development.md, docs/documentation/pytest_hardpy.md, docs/examples/multiple_stands.md, docs/examples/operator_msg.md, docs/index.md
1. Removed the name **HardPy** from the index page.
2. Replaced `hardpy-panel` with `hardpy init` or `hardpy run` commands.
3. Changed some minor details.
=> Fix some documentation details

README.md, docs/documentation/index.md, docs/examples/index.md, mkdocs.yml
* Fix the structure image path.
* Add `index.md` for **documentation** and **examples** sections.
=> Fix the structure image

docs/changelog.md, hardpy/pytest_hardpy/plugin.py
Fix skipped test case and module status. Now status of skipped test is **skipped**, not **ready**.
Problem artifact:
```json
{
"_id": "current",
"_rev": "2829-d2674ae2a652c10fdd530edef3fc38e7",
"modules": {
"test_2": {
"status": "failed",
"name": "Main tests",
"start_time": 1730357474,
"stop_time": 1730357474,
"cases": {
"test_minute_parity": {
"status": "failed",
"name": "Minute check",
"start_time": 1730357474,
"stop_time": 1730357474,
"assertion_msg": "AssertionError: The test failed because 51 is odd! Try again!\nassert 1 == 0",
"msg": {
"d5df6710-2d30-4061-93b8-8bc2b3389d27": "Current minute 51"
},
"artifact": {
"minute": 51
}
}
},
"artifact": {}
},
"test_3": {
"status": "ready",
"name": "End of testing",
"start_time": null,
"stop_time": null,
"cases": {
"test_one": {
"status": …
```
=> Fix skipped test case and module status

hardpy/hardpy_panel/frontend/src/hardpy_test_view/DialogBox.tsx
- window height indent decreased
- text line height for calculation decreased
- window fill with picture parameter replaced
- height indent increased in dialog boxes with multiple steps
=> Correct sizes of dialog box with images 

.github/workflows/release.yml
Update gh-action-sigstore-python to 3.0.0
Problem: https://github.com/everypinio/hardpy/actions/runs/12370737075/job/34525522403
Result: https://github.com/xorialexandrov/hardpy/actions/runs/12371271064/job/34527138466
=> Update gh-action-sigstore-python to 3.0.0

docs/documentation/database.md, docs/documentation/hardpy_panel.md, docs/examples/operator_msg.md
- replace images links in documentation
- make the entire image the same format and centered
=> Correct images links

.vscode/.gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json, docs/about/development.md, hardpy/hardpy_panel/api.py, hardpy/hardpy_panel/frontend/.eslintrc, hardpy/hardpy_panel/frontend/package.json, scripts/compile_front.sh, scripts/recompile_front.sh
Add development mode
To edit the frontend, you can use the debugging mode in Visual Studio Code (VSCode). To do this, you need to run the following configurations in the VSCode debugger:
1. **Run Frontend**: This configuration is responsible for starting the frontend application.
2. **Debug Frontend**: This configuration is used to debug the frontend application in the Chrome browser. 
3. Any example, such as a Dialog Box (the DB should be running beforehand).
=> Add development mode

pyproject.toml
Update hatching build backend to 1.27.0 for updating package metadata from 2.1 to 2.4.
* Problem action: https://github.com/everypinio/hardpy/actions/runs/13631849618/job/38101326961
`hatching==1.21.1` metadata info:
```
Metadata-Version: 2.1
Name: hardpy
Version: 0.10.0
```
`hatching==1.27.0` metadata info:
```
Metadata-Version: 2.4
Name: hardpy
Version: 0.10.0
```
=> Update hatchling to 1.27.0

docs/changelog.md, pyproject.toml
1. Remove the internal **HardPy** socket on port 6525. Pytest plugin arguments `--hardpy-sh` and `--hardpy-sp`
are left for backward compatibility with version below 0.10.1. #114
2. Add the ability to add HTML pages using `HTMLComponent` to dialog boxes and operator messages. #104 
* Removed the internal **HardPy** socket on port 6525. 
* Pytest plugin arguments `--hardpy-sh` and `--hardpy-sp` are left for backward compatibility with version below 0.10.1.
* When the major version is released, it is necessary to remove these args from **plugin.py**. A **TODO** note was left about it.
* Removed `[socket]` section from the **hardpy.toml** file.
* Added `update_doc_by_db` function for document synchronization in some reporter instances.
* Documentation and tests updated. 
* Added the ability …
=> 0.11.0 package update

hardpy/common/stand_cloud/connector.py, hardpy/pytest_hardpy/result/report_loader/stand_cloud_loader.py
* Rename `test_run` **StandCloud** endpoints: `api/test_run` -> `test_run`.
* Rename the **StandCloud** API address to `hardpy`. The API is now service independent.
=> StandCloud endpoints renaming

.ruff.toml, .vscode/launch.json, docs/changelog.md, docs/documentation/cli.md, docs/documentation/hardpy_config.md, docs/documentation/pytest_hardpy.md, docs/examples/hardpy_launch.md, docs/features/features.md, hardpy/cli/cli.py, hardpy/common/config.py, hardpy/hardpy_panel/api.py, hardpy/pytest_hardpy/plugin.py, hardpy/pytest_hardpy/pytest_wrapper.py, tests/test_common/test_config.py
Added the `tests_name` field to **hardpy.toml**. The `tests_name` allows to name the test suite in the operator panel. 
**hardpy.toml** file in the minute_parity directory:
```toml
title = "HardPy TOML config"
tests_dir = "minute_parity"
tests_name = "Minute Parity"
...
```
Operator panel with the  name "**Minute Parity**":
Added CLI commands: `hardpy start`, `hardpy stop` and `hardpy status`. 
* The `hardpy start` command is used to launch **HardPy** tests while the **HardPy** opener panel is running.
* The `hardpy stop` command is used to stop **HardPy** tests while the **HardPy** opener panel is running.
* The `hardpy status` command is used to stop **HardPy** tests while the **HardPy** opener panel is running.
=> Tests name and new CLI commands

docs/changelog.md, hardpy/pytest_hardpy/plugin.py, tests/test_plugin/test_dependency.py
In modules where the final test was dependent on another test and was not executed at the end, the module **stop_time** was not filled in.
1. In cases where the **HardpyPlugin** plugin skips a test, the **start_time** and **stop_time** of the test are not filled. Module  **start_time** and **stop_time** are filled in.
2. In cases where user skip test via a self-call to `pytest.skip()`, the **start_time** and **stop_time** in case and module filled in. 
```python
import pytest
import hardpy
def test_one():
assert False
@pytest.mark.dependency("test_1::test_one")
def test_two():
assert True
```
Problem in the database with **test_1** module **stop_time**:
```json
{
"_id": "current",
"_rev": "10484-a5e517416d9b8c0fe7b1fe43d83489f2",
"modules": {
"test_1": {
"status": "skipped",
"name": …
```
=> Zero module stop time in skip test

docs/examples/stand_cloud_reader.md
Fix **StandCloud** `test_run` response example. Remove excess fieds from `dut_info`.
=> Fix StandCloud `test_run` response example

docs/changelog.md, docs/documentation/pytest_hardpy.md, hardpy/hardpy_panel/frontend/src/button/StartStop.tsx, hardpy/pytest_hardpy/plugin.py, hardpy/pytest_hardpy/pytest_call.py, hardpy/pytest_hardpy/reporter/base.py, hardpy/pytest_hardpy/reporter/hook_reporter.py
* Update the status of the test case and module when the test stops. Only one case and one module receive the "stopped" status, while the rest are marked as "skipped."
* Add an alert to operator panel when the following are called not from tests: `set_message`, `set_case_artifact`, `set_module_artifact`, `run_dialog_box`, and `get_current_attempt`.
* Add a pause to avoid double clicking the stop button.
=> Update the status of the stopped tests

docs/changelog.md, hardpy/common/stand_cloud/connector.py, hardpy/common/stand_cloud/registration.py, pyproject.toml
Update package to 0.13.0
Authorization has been replaced by the OAuth 2.0 device flow. **There is no backward compatibility with the previous authorization version.**
* The OAuth2 callback page has been removed from the **HardPy** side during authorization.
* Added QR code output for authorization from third-party devices if the user cannot access a browser on a device running HardPy.
* Added the ability to log in to multiple **StandCloud** instances.
* Logout of **StandCloud** now requires the address of a **StandCloud** instance. For example:
```bash
hardpy sc-logout demo.standcloud.io
```
* Added examples of working with authorization for third-party applications.
* `ruff` in CI is configured for the **HardPy** folder only.
* Update the status of the test case and module when the test …
=> Update package to 0.13.0

docs/changelog.md, hardpy/pytest_hardpy/result/report_loader/stand_cloud_loader.py
* Add a timeout to the `load` function of the `StandCloudLoader` class.
* The high default timeout value (20 seconds) is useful for poor network connections at the factory.
=> Timeout to the load function of the StandCloudLoader class

docs/changelog.md, docs/documentation/hardpy_config.md, examples/attempts/hardpy.toml, examples/couchdb_load/hardpy.toml, examples/dialog_box/hardpy.toml, examples/hello_hardpy/hardpy.toml, examples/measurement/hardpy.toml, examples/minute_parity/hardpy.toml, examples/operator_msg/hardpy.toml, examples/stand_cloud/hardpy.toml, hardpy/cli/cli.py, hardpy/common/config.py, tests/test_cli/test_cmd/conftest.py, tests/test_common/test_config.py, tests/test_plugin/hardpy.toml, tests/test_plugin/test_func.py
The `tests_dir` variable was removed from **hardpy.toml** because it is obsolete and unused.
ISSUE: https://github.com/everypinio/hardpy/issues/155
The `ConfigData` test was removed. The `ConfigData` class does not exist.
Added a manual marker to the **pytest** configuration in `test_cmd`.
=> Remove tests_dir
